### ISSUE TITLE
I'm have a little issue

### ISSUE THREAD

**Issue by LoneSparow** [DrewTheGhost/StardewPlanner#2]
Ok, a friend recommended this to me and he talked about how he couldn't find any bodacious babes and I honestly doubted him. I thought he was just blind and couldn't find them, but the more time I had in the game the more I realized he might be right so I looked around the forums and it is littered with posts about missing babes. So, I decided to go to the source, to the creator. Ok man WHERE ARE THE BABES. This is less of a complaint and more of a concern. You said in your dev thoughts that babes would be here by now but there are no babes insight. Please bro, the people want this. They NEED this.

Much love "Concerned Player"

**Comment by Darthpumkins** [comment]
Who're you?

**Comment by LoneSparow** [comment]
who are you?
