### ISSUE TITLE
Software Works Well, Missing One Key Feature

### ISSUE THREAD

**Issue by Tlertalks** [DrewTheGhost/StardewPlanner#3]
So I'm really enjoying this software, it's just got one glaring issue that keeps it from being perfect. There's one feature that almost every competitor has, for good reason i might add, that this piece of software is missing. Where are the babes? Seriously, in this day and age, seriously?? Why am i gonna use a piece of software that doesnt contain babes for me to gawk at and crank my hog to.

**Comment by Darthpumkins** [comment]
Why're you crying in your picture?

**Comment by zoe-svg** [comment]
Having same issue. Bumping for visibility

**Comment by Tlertalks** [comment]
> Why're you crying in your picture?

Opened up StardewPlanner and didn't see any babes for like 30 minutes straight, got a little bit emotional.

**Comment by LoneSparow** [comment]
> Why're you crying in your picture?

Why do I see you every were, WHO ARE YOU!!!!
